runtime: python39
env: standard

handlers:
  - url: /.*
    script: auto

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.8
  min_instances: 1
  max_instances: 2

runtime_config:
  python_version: 3

env_variables:
  DJANGO_SETTINGS_MODULE: "main.settings.dynamic"

entrypoint: gunicorn -b :$PORT main.wsgi:application
